version: "3.7"

services:
    front:
        container_name: video-chat-front
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
