version: "3"

services:
    sample:
        container_name: video_chat_front
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        restart: always
